# Project 3

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv(r"C:\Users\Asus\Downloads\data analytics project 1\project analysis python\AI_Impact_on_Human_Mental_Growth.csv")
df

,Row_ID,Year,Era,Scenario,Region,Demographic_Group,Education_Level,Profession,AI_Tool_Category,Weekly_AI_Usage_Hours,...,Human_Decision_Making_Involvement,Social_Interaction_Quality,Cognitive_Load_Index,Mental_Wellbeing_Score,AI_Tool_Proficiency,Adaptability_Score,Attention_Span_Minutes,Positive_Effects_of_AI,Negative_Effects_of_AI,Outcome_Label
0,1,2064,Symbiotic Intelligence Age,Pessimistic,East Asia,Young Adult (26-35),Undergraduate,Technology,AGI-Adjacent Tools,28.2,...,45.15,43.94,75.10,47.70,64.66,40.02,24.16,Cross-domain creativity boosts,Reduced independent thinking; Algorithmic bias...,Cognitive Decline Risk
1,2,2029,AI Mainstream Adoption,Mixed,Latin America,Senior (51-65),Undergraduate,Healthcare,NaN,10.0,...,82.28,70.24,52.64,74.85,28.18,57.00,46.35,Democratized access to expertise; Broader know...,Memory atrophy from AI offloading,Stagnant / Moderate
2,3,2047,Post-Singularity Transition,Neutral,Latin America,Youth (18-25),Secondary,Science & Research,Analytical AI,28.0,...,68.87,67.20,60.50,82.08,42.99,56.79,37.30,Faster skill acquisition,Privacy erosion through behavioral data,Stagnant / Moderate
3,4,2069,Symbiotic Intelligence Age,Neutral,East Asia,Senior (51-65),PhD/Research,Technology,Full AGI Integration,35.2,...,55.05,59.41,60.15,55.34,66.65,65.33,56.93,Reduced cognitive load on repetitive tasks,Decreased social bonding,Positive Growth
4,5,2048,Post-Singularity Transition,Optimistic,South Asia,Young Adult (26-35),Undergraduate,Entrepreneurship,Multi-modal AI,24.4,...,73.01,67.83,61.62,77.47,50.39,75.56,42.53,Increased productivity for deep work; Reduced ...,NaN,Positive Growth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51995,51996,2069,Symbiotic Intelligence Age,Mixed,South Asia,Young Adult (26-35),PhD/Research,Technology,Full AGI Integration,44.6,...,54.87,70.23,74.96,69.43,78.25,51.84,43.29,Faster skill acquisition,Algorithmic bias reinforcement; Memory atrophy...,Stagnant / Moderate
51996,51997,2052,Cognitive Co-Evolution,Pessimistic,South Asia,Youth (18-25),PhD/Research,Skilled Trades,Multi-modal AI,34.4,...,77.48,59.25,71.73,39.15,66.04,59.52,37.75,NaN,Algorithmic bias reinforcement; Digital addict...,Cognitive Decline Risk
51997,51998,2034,AI-Augmented Society,Mixed,Southeast Asia,Young Adult (26-35),Undergraduate,Technology,Basic Assistants,7.9,...,68.04,73.49,56.73,59.71,25.88,52.13,42.74,Greater scientific discovery rates,Memory atrophy from AI offloading,Stagnant / Moderate
51998,51999,2063,Symbiotic Intelligence Age,Mixed,Europe,Elder (65+),Primary,Business,Full AGI Integration,38.1,...,83.96,63.76,75.91,65.16,86.20,60.20,47.62,Personalized learning pathways; Increased prod...,Skill atrophy in non-AI domains; Declining han...,Stagnant / Moderate
51999,52000,2052,Cognitive Co-Evolution,Pessimistic,East Asia,Adult (36-50),Primary,Engineering,Multi-modal AI,31.7,...,53.57,50.89,72.67,50.12,73.36,45.66,18.42,Greater scientific discovery rates,Polarization through AI echo chambers; Reduced...,Cognitive Decline Risk

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 27 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Row_ID                             52000 non-null  int64
 1   Year                               52000 non-null  int64
 2   Era                                52000 non-null  object
 3   Scenario                           52000 non-null  object
 4   Region                             52000 non-null  object
 5   Demographic_Group                  52000 non-null  object
 6   Education_Level                    52000 non-null  object
 7   Profession                         52000 non-null  object
 8   AI_Tool_Category                   44286 non-null  object
 9   Weekly_AI_Usage_Hours              52000 non-null  float64
 10  AI_Dependency_Score                52000 non-null  float64
 11  Human_Creativity_Score             52000 non-null  float64
 12  Critical_Thinking_Ability          52000 non-null  float64
 13  Problem_Solving_Skills             52000 non-null  float64
 14  Emotional_Intelligence             52000 non-null  float64
 15  Innovation_Rate                    52000 non-null  float64
 16  Learning_Speed                     52000 non-null  float64
 17  Human_Decision_Making_Involvement  52000 non-null  float64
 18  Social_Interaction_Quality         52000 non-null  float64
 19  Cognitive_Load_Index               52000 non-null  float64
 20  Mental_Wellbeing_Score             52000 non-null  float64
 21  AI_Tool_Proficiency                52000 non-null  float64
 22  Adaptability_Score                 52000 non-null  float64
 23  Attention_Span_Minutes             52000 non-null  float64
 24  Positive_Effects_of_AI             47051 non-null  object
 25  Negative_Effects_of_AI             47094 non-null  object
 26  Outcome_Label                      52000 non-null  object
dtypes: float64(15), int64(2), object(10)
memory usage: 10.7+ MB

In [4]:
df.describe()

,Row_ID,Year,Weekly_AI_Usage_Hours,AI_Dependency_Score,Human_Creativity_Score,Critical_Thinking_Ability,Problem_Solving_Skills,Emotional_Intelligence,Innovation_Rate,Learning_Speed,Human_Decision_Making_Involvement,Social_Interaction_Quality,Cognitive_Load_Index,Mental_Wellbeing_Score,AI_Tool_Proficiency,Adaptability_Score,Attention_Span_Minutes
count,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000
mean,26000.500000,2049.493077,24.568075,49.063843,63.437188,63.135306,65.185583,63.828012,56.883659,64.704454,68.113805,64.258143,64.749945,62.867952,51.711476,62.384537,44.972622
std,15011.251336,15.027805,11.923980,21.789630,12.205201,12.404421,12.132950,10.747375,15.485854,12.416813,13.417990,11.357260,8.875470,11.517207,19.448359,12.018638,12.339129
min,1.000000,2024.000000,0.000000,0.110000,10.310000,12.760000,13.350000,13.990000,0.000000,17.300000,5.080000,13.990000,34.410000,14.160000,0.000000,18.200000,5.000000
25%,13000.750000,2036.000000,15.300000,31.170000,56.520000,57.110000,57.300000,58.170000,46.130000,55.770000,60.050000,58.320000,58.410000,56.210000,36.280000,54.767500,36.827500
50%,26000.500000,2049.000000,24.500000,49.045000,64.810000,63.780000,65.740000,65.050000,57.100000,63.670000,69.570000,64.850000,64.740000,63.810000,51.650000,62.180000,45.820000
75%,39000.250000,2063.000000,33.700000,67.070000,71.450000,70.850000,72.910000,70.670000,66.862500,72.960000,77.530000,71.830000,71.030000,70.690000,67.040000,69.920000,53.910000
max,52000.000000,2075.000000,62.200000,99.960000,100.000000,100.000000,100.000000,97.670000,100.000000,100.000000,100.000000,97.870000,98.470000,98.250000,100.000000,100.000000,86.590000

In [5]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51995    False
51996    False
51997    False
51998    False
51999    False
Length: 52000, dtype: bool

In [6]:
df.isnull().mean()

Row_ID                               0.000000
Year                                 0.000000
Era                                  0.000000
Scenario                             0.000000
Region                               0.000000
Demographic_Group                    0.000000
Education_Level                      0.000000
Profession                           0.000000
AI_Tool_Category                     0.148346
Weekly_AI_Usage_Hours                0.000000
AI_Dependency_Score                  0.000000
Human_Creativity_Score               0.000000
Critical_Thinking_Ability            0.000000
Problem_Solving_Skills               0.000000
Emotional_Intelligence               0.000000
Innovation_Rate                      0.000000
Learning_Speed                       0.000000
Human_Decision_Making_Involvement    0.000000
Social_Interaction_Quality           0.000000
Cognitive_Load_Index                 0.000000
Mental_Wellbeing_Score               0.000000
AI_Tool_Proficiency                  0.000000
Adaptability_Score                   0.000000
Attention_Span_Minutes               0.000000
Positive_Effects_of_AI               0.095173
Negative_Effects_of_AI               0.094346
Outcome_Label                        0.000000
dtype: float64

In [7]:
df

,Row_ID,Year,Era,Scenario,Region,Demographic_Group,Education_Level,Profession,AI_Tool_Category,Weekly_AI_Usage_Hours,...,Human_Decision_Making_Involvement,Social_Interaction_Quality,Cognitive_Load_Index,Mental_Wellbeing_Score,AI_Tool_Proficiency,Adaptability_Score,Attention_Span_Minutes,Positive_Effects_of_AI,Negative_Effects_of_AI,Outcome_Label
0,1,2064,Symbiotic Intelligence Age,Pessimistic,East Asia,Young Adult (26-35),Undergraduate,Technology,AGI-Adjacent Tools,28.2,...,45.15,43.94,75.10,47.70,64.66,40.02,24.16,Cross-domain creativity boosts,Reduced independent thinking; Algorithmic bias...,Cognitive Decline Risk
1,2,2029,AI Mainstream Adoption,Mixed,Latin America,Senior (51-65),Undergraduate,Healthcare,NaN,10.0,...,82.28,70.24,52.64,74.85,28.18,57.00,46.35,Democratized access to expertise; Broader know...,Memory atrophy from AI offloading,Stagnant / Moderate
2,3,2047,Post-Singularity Transition,Neutral,Latin America,Youth (18-25),Secondary,Science & Research,Analytical AI,28.0,...,68.87,67.20,60.50,82.08,42.99,56.79,37.30,Faster skill acquisition,Privacy erosion through behavioral data,Stagnant / Moderate
3,4,2069,Symbiotic Intelligence Age,Neutral,East Asia,Senior (51-65),PhD/Research,Technology,Full AGI Integration,35.2,...,55.05,59.41,60.15,55.34,66.65,65.33,56.93,Reduced cognitive load on repetitive tasks,Decreased social bonding,Positive Growth
4,5,2048,Post-Singularity Transition,Optimistic,South Asia,Young Adult (26-35),Undergraduate,Entrepreneurship,Multi-modal AI,24.4,...,73.01,67.83,61.62,77.47,50.39,75.56,42.53,Increased productivity for deep work; Reduced ...,NaN,Positive Growth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51995,51996,2069,Symbiotic Intelligence Age,Mixed,South Asia,Young Adult (26-35),PhD/Research,Technology,Full AGI Integration,44.6,...,54.87,70.23,74.96,69.43,78.25,51.84,43.29,Faster skill acquisition,Algorithmic bias reinforcement; Memory atrophy...,Stagnant / Moderate
51996,51997,2052,Cognitive Co-Evolution,Pessimistic,South Asia,Youth (18-25),PhD/Research,Skilled Trades,Multi-modal AI,34.4,...,77.48,59.25,71.73,39.15,66.04,59.52,37.75,NaN,Algorithmic bias reinforcement; Digital addict...,Cognitive Decline Risk
51997,51998,2034,AI-Augmented Society,Mixed,Southeast Asia,Young Adult (26-35),Undergraduate,Technology,Basic Assistants,7.9,...,68.04,73.49,56.73,59.71,25.88,52.13,42.74,Greater scientific discovery rates,Memory atrophy from AI offloading,Stagnant / Moderate
51998,51999,2063,Symbiotic Intelligence Age,Mixed,Europe,Elder (65+),Primary,Business,Full AGI Integration,38.1,...,83.96,63.76,75.91,65.16,86.20,60.20,47.62,Personalized learning pathways; Increased prod...,Skill atrophy in non-AI domains; Declining han...,Stagnant / Moderate
51999,52000,2052,Cognitive Co-Evolution,Pessimistic,East Asia,Adult (36-50),Primary,Engineering,Multi-modal AI,31.7,...,53.57,50.89,72.67,50.12,73.36,45.66,18.42,Greater scientific discovery rates,Polarization through AI echo chambers; Reduced...,Cognitive Decline Risk

In [8]:
df.rename(columns = {'Year':'Tahun', 'Era':'Masa', 'Scenario':'Skenario'})

,Row_ID,Tahun,Masa,Skenario,Region,Demographic_Group,Education_Level,Profession,AI_Tool_Category,Weekly_AI_Usage_Hours,...,Human_Decision_Making_Involvement,Social_Interaction_Quality,Cognitive_Load_Index,Mental_Wellbeing_Score,AI_Tool_Proficiency,Adaptability_Score,Attention_Span_Minutes,Positive_Effects_of_AI,Negative_Effects_of_AI,Outcome_Label
0,1,2064,Symbiotic Intelligence Age,Pessimistic,East Asia,Young Adult (26-35),Undergraduate,Technology,AGI-Adjacent Tools,28.2,...,45.15,43.94,75.10,47.70,64.66,40.02,24.16,Cross-domain creativity boosts,Reduced independent thinking; Algorithmic bias...,Cognitive Decline Risk
1,2,2029,AI Mainstream Adoption,Mixed,Latin America,Senior (51-65),Undergraduate,Healthcare,NaN,10.0,...,82.28,70.24,52.64,74.85,28.18,57.00,46.35,Democratized access to expertise; Broader know...,Memory atrophy from AI offloading,Stagnant / Moderate
2,3,2047,Post-Singularity Transition,Neutral,Latin America,Youth (18-25),Secondary,Science & Research,Analytical AI,28.0,...,68.87,67.20,60.50,82.08,42.99,56.79,37.30,Faster skill acquisition,Privacy erosion through behavioral data,Stagnant / Moderate
3,4,2069,Symbiotic Intelligence Age,Neutral,East Asia,Senior (51-65),PhD/Research,Technology,Full AGI Integration,35.2,...,55.05,59.41,60.15,55.34,66.65,65.33,56.93,Reduced cognitive load on repetitive tasks,Decreased social bonding,Positive Growth
4,5,2048,Post-Singularity Transition,Optimistic,South Asia,Young Adult (26-35),Undergraduate,Entrepreneurship,Multi-modal AI,24.4,...,73.01,67.83,61.62,77.47,50.39,75.56,42.53,Increased productivity for deep work; Reduced ...,NaN,Positive Growth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51995,51996,2069,Symbiotic Intelligence Age,Mixed,South Asia,Young Adult (26-35),PhD/Research,Technology,Full AGI Integration,44.6,...,54.87,70.23,74.96,69.43,78.25,51.84,43.29,Faster skill acquisition,Algorithmic bias reinforcement; Memory atrophy...,Stagnant / Moderate
51996,51997,2052,Cognitive Co-Evolution,Pessimistic,South Asia,Youth (18-25),PhD/Research,Skilled Trades,Multi-modal AI,34.4,...,77.48,59.25,71.73,39.15,66.04,59.52,37.75,NaN,Algorithmic bias reinforcement; Digital addict...,Cognitive Decline Risk
51997,51998,2034,AI-Augmented Society,Mixed,Southeast Asia,Young Adult (26-35),Undergraduate,Technology,Basic Assistants,7.9,...,68.04,73.49,56.73,59.71,25.88,52.13,42.74,Greater scientific discovery rates,Memory atrophy from AI offloading,Stagnant / Moderate
51998,51999,2063,Symbiotic Intelligence Age,Mixed,Europe,Elder (65+),Primary,Business,Full AGI Integration,38.1,...,83.96,63.76,75.91,65.16,86.20,60.20,47.62,Personalized learning pathways; Increased prod...,Skill atrophy in non-AI domains; Declining han...,Stagnant / Moderate
51999,52000,2052,Cognitive Co-Evolution,Pessimistic,East Asia,Adult (36-50),Primary,Engineering,Multi-modal AI,31.7,...,53.57,50.89,72.67,50.12,73.36,45.66,18.42,Greater scientific discovery rates,Polarization through AI echo chambers; Reduced...,Cognitive Decline Risk

In [9]:
df.set_index('Region')

,Row_ID,Year,Era,Scenario,Demographic_Group,Education_Level,Profession,AI_Tool_Category,Weekly_AI_Usage_Hours,AI_Dependency_Score,...,Human_Decision_Making_Involvement,Social_Interaction_Quality,Cognitive_Load_Index,Mental_Wellbeing_Score,AI_Tool_Proficiency,Adaptability_Score,Attention_Span_Minutes,Positive_Effects_of_AI,Negative_Effects_of_AI,Outcome_Label
Region,,,,,,,,,,,,,,,,,,,,,
East Asia,1,2064,Symbiotic Intelligence Age,Pessimistic,Young Adult (26-35),Undergraduate,Technology,AGI-Adjacent Tools,28.2,71.57,...,45.15,43.94,75.10,47.70,64.66,40.02,24.16,Cross-domain creativity boosts,Reduced independent thinking; Algorithmic bias...,Cognitive Decline Risk
Latin America,2,2029,AI Mainstream Adoption,Mixed,Senior (51-65),Undergraduate,Healthcare,NaN,10.0,16.36,...,82.28,70.24,52.64,74.85,28.18,57.00,46.35,Democratized access to expertise; Broader know...,Memory atrophy from AI offloading,Stagnant / Moderate
Latin America,3,2047,Post-Singularity Transition,Neutral,Youth (18-25),Secondary,Science & Research,Analytical AI,28.0,40.70,...,68.87,67.20,60.50,82.08,42.99,56.79,37.30,Faster skill acquisition,Privacy erosion through behavioral data,Stagnant / Moderate
East Asia,4,2069,Symbiotic Intelligence Age,Neutral,Senior (51-65),PhD/Research,Technology,Full AGI Integration,35.2,70.65,...,55.05,59.41,60.15,55.34,66.65,65.33,56.93,Reduced cognitive load on repetitive tasks,Decreased social bonding,Positive Growth
South Asia,5,2048,Post-Singularity Transition,Optimistic,Young Adult (26-35),Undergraduate,Entrepreneurship,Multi-modal AI,24.4,41.76,...,73.01,67.83,61.62,77.47,50.39,75.56,42.53,Increased productivity for deep work; Reduced ...,NaN,Positive Growth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
South Asia,51996,2069,Symbiotic Intelligence Age,Mixed,Young Adult (26-35),PhD/Research,Technology,Full AGI Integration,44.6,86.29,...,54.87,70.23,74.96,69.43,78.25,51.84,43.29,Faster skill acquisition,Algorithmic bias reinforcement; Memory atrophy...,Stagnant / Moderate
South Asia,51997,2052,Cognitive Co-Evolution,Pessimistic,Youth (18-25),PhD/Research,Skilled Trades,Multi-modal AI,34.4,67.55,...,77.48,59.25,71.73,39.15,66.04,59.52,37.75,NaN,Algorithmic bias reinforcement; Digital addict...,Cognitive Decline Risk
Southeast Asia,51998,2034,AI-Augmented Society,Mixed,Young Adult (26-35),Undergraduate,Technology,Basic Assistants,7.9,28.41,...,68.04,73.49,56.73,59.71,25.88,52.13,42.74,Greater scientific discovery rates,Memory atrophy from AI offloading,Stagnant / Moderate
Europe,51999,2063,Symbiotic Intelligence Age,Mixed,Elder (65+),Primary,Business,Full AGI Integration,38.1,77.20,...,83.96,63.76,75.91,65.16,86.20,60.20,47.62,Personalized learning pathways; Increased prod...,Skill atrophy in non-AI domains; Declining han...,Stagnant / Moderate
East Asia,52000,2052,Cognitive Co-Evolution,Pessimistic,Adult (36-50),Primary,Engineering,Multi-modal AI,31.7,64.81,...,53.57,50.89,72.67,50.12,73.36,45.66,18.42,Greater scientific discovery rates,Polarization through AI echo chambers; Reduced...,Cognitive Decline Risk

In [25]:
df.pivot_table(index= 'Demographic_Group', columns= 'Region',values= 'Weekly_AI_Usage_Hours')

Region,Africa,East Asia,Europe,Latin America,Middle East,North America,Oceania,South Asia,Southeast Asia
Demographic_Group,,,,,,,,,
Adult (36-50),24.585389,24.294850,24.527521,25.261374,25.321289,24.598361,24.642774,24.895341,24.852251
Elder (65+),23.970052,24.389580,24.660051,24.098309,24.016637,24.607611,24.376740,24.857241,24.651043
Senior (51-65),24.013386,24.302726,24.412999,24.859445,24.193523,24.852632,24.967313,24.550613,24.390628
Young Adult (26-35),24.384228,23.826463,23.966943,24.787544,24.593707,25.130177,24.988808,24.783731,24.365013
Youth (18-25),24.896777,24.418966,25.014662,24.321913,24.373427,24.431771,25.143034,24.476000,24.547432

In [4]:
df

,Row_ID,Year,Era,Scenario,Region,Demographic_Group,Education_Level,Profession,AI_Tool_Category,Weekly_AI_Usage_Hours,...,Human_Decision_Making_Involvement,Social_Interaction_Quality,Cognitive_Load_Index,Mental_Wellbeing_Score,AI_Tool_Proficiency,Adaptability_Score,Attention_Span_Minutes,Positive_Effects_of_AI,Negative_Effects_of_AI,Outcome_Label
0,1,2064,Symbiotic Intelligence Age,Pessimistic,East Asia,Young Adult (26-35),Undergraduate,Technology,AGI-Adjacent Tools,28.2,...,45.15,43.94,75.10,47.70,64.66,40.02,24.16,Cross-domain creativity boosts,Reduced independent thinking; Algorithmic bias...,Cognitive Decline Risk
1,2,2029,AI Mainstream Adoption,Mixed,Latin America,Senior (51-65),Undergraduate,Healthcare,NaN,10.0,...,82.28,70.24,52.64,74.85,28.18,57.00,46.35,Democratized access to expertise; Broader know...,Memory atrophy from AI offloading,Stagnant / Moderate
2,3,2047,Post-Singularity Transition,Neutral,Latin America,Youth (18-25),Secondary,Science & Research,Analytical AI,28.0,...,68.87,67.20,60.50,82.08,42.99,56.79,37.30,Faster skill acquisition,Privacy erosion through behavioral data,Stagnant / Moderate
3,4,2069,Symbiotic Intelligence Age,Neutral,East Asia,Senior (51-65),PhD/Research,Technology,Full AGI Integration,35.2,...,55.05,59.41,60.15,55.34,66.65,65.33,56.93,Reduced cognitive load on repetitive tasks,Decreased social bonding,Positive Growth
4,5,2048,Post-Singularity Transition,Optimistic,South Asia,Young Adult (26-35),Undergraduate,Entrepreneurship,Multi-modal AI,24.4,...,73.01,67.83,61.62,77.47,50.39,75.56,42.53,Increased productivity for deep work; Reduced ...,NaN,Positive Growth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51995,51996,2069,Symbiotic Intelligence Age,Mixed,South Asia,Young Adult (26-35),PhD/Research,Technology,Full AGI Integration,44.6,...,54.87,70.23,74.96,69.43,78.25,51.84,43.29,Faster skill acquisition,Algorithmic bias reinforcement; Memory atrophy...,Stagnant / Moderate
51996,51997,2052,Cognitive Co-Evolution,Pessimistic,South Asia,Youth (18-25),PhD/Research,Skilled Trades,Multi-modal AI,34.4,...,77.48,59.25,71.73,39.15,66.04,59.52,37.75,NaN,Algorithmic bias reinforcement; Digital addict...,Cognitive Decline Risk
51997,51998,2034,AI-Augmented Society,Mixed,Southeast Asia,Young Adult (26-35),Undergraduate,Technology,Basic Assistants,7.9,...,68.04,73.49,56.73,59.71,25.88,52.13,42.74,Greater scientific discovery rates,Memory atrophy from AI offloading,Stagnant / Moderate
51998,51999,2063,Symbiotic Intelligence Age,Mixed,Europe,Elder (65+),Primary,Business,Full AGI Integration,38.1,...,83.96,63.76,75.91,65.16,86.20,60.20,47.62,Personalized learning pathways; Increased prod...,Skill atrophy in non-AI domains; Declining han...,Stagnant / Moderate
51999,52000,2052,Cognitive Co-Evolution,Pessimistic,East Asia,Adult (36-50),Primary,Engineering,Multi-modal AI,31.7,...,53.57,50.89,72.67,50.12,73.36,45.66,18.42,Greater scientific discovery rates,Polarization through AI echo chambers; Reduced...,Cognitive Decline Risk

# pilih kolom, hapus kolom, tambah kolom, stat corr, vis:  bar and line chart

In [7]:
df[['Year','Region','Profession']]

       Year          Region          Profession
0      2064       East Asia          Technology
1      2029   Latin America          Healthcare
2      2047   Latin America  Science & Research
3      2069       East Asia          Technology
4      2048      South Asia    Entrepreneurship
...     ...             ...                 ...
51995  2069      South Asia          Technology
51996  2052      South Asia      Skilled Trades
51997  2034  Southeast Asia          Technology
51998  2063          Europe            Business
51999  2052       East Asia         Engineering

[52000 rows x 3 columns]

In [19]:
df

,Row_ID,Year,Era,Scenario,Region,Demographic_Group,Education_Level,Profession,AI_Tool_Category,Weekly_AI_Usage_Hours,...,Human_Decision_Making_Involvement,Social_Interaction_Quality,Cognitive_Load_Index,Mental_Wellbeing_Score,AI_Tool_Proficiency,Adaptability_Score,Attention_Span_Minutes,Positive_Effects_of_AI,Negative_Effects_of_AI,Outcome_Label
0,1,2064,Symbiotic Intelligence Age,Pessimistic,East Asia,Young Adult (26-35),Undergraduate,Technology,AGI-Adjacent Tools,28.2,...,45.15,43.94,75.10,47.70,64.66,40.02,24.16,Cross-domain creativity boosts,Reduced independent thinking; Algorithmic bias...,Cognitive Decline Risk
1,2,2029,AI Mainstream Adoption,Mixed,Latin America,Senior (51-65),Undergraduate,Healthcare,NaN,10.0,...,82.28,70.24,52.64,74.85,28.18,57.00,46.35,Democratized access to expertise; Broader know...,Memory atrophy from AI offloading,Stagnant / Moderate
2,3,2047,Post-Singularity Transition,Neutral,Latin America,Youth (18-25),Secondary,Science & Research,Analytical AI,28.0,...,68.87,67.20,60.50,82.08,42.99,56.79,37.30,Faster skill acquisition,Privacy erosion through behavioral data,Stagnant / Moderate
3,4,2069,Symbiotic Intelligence Age,Neutral,East Asia,Senior (51-65),PhD/Research,Technology,Full AGI Integration,35.2,...,55.05,59.41,60.15,55.34,66.65,65.33,56.93,Reduced cognitive load on repetitive tasks,Decreased social bonding,Positive Growth
4,5,2048,Post-Singularity Transition,Optimistic,South Asia,Young Adult (26-35),Undergraduate,Entrepreneurship,Multi-modal AI,24.4,...,73.01,67.83,61.62,77.47,50.39,75.56,42.53,Increased productivity for deep work; Reduced ...,NaN,Positive Growth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51995,51996,2069,Symbiotic Intelligence Age,Mixed,South Asia,Young Adult (26-35),PhD/Research,Technology,Full AGI Integration,44.6,...,54.87,70.23,74.96,69.43,78.25,51.84,43.29,Faster skill acquisition,Algorithmic bias reinforcement; Memory atrophy...,Stagnant / Moderate
51996,51997,2052,Cognitive Co-Evolution,Pessimistic,South Asia,Youth (18-25),PhD/Research,Skilled Trades,Multi-modal AI,34.4,...,77.48,59.25,71.73,39.15,66.04,59.52,37.75,NaN,Algorithmic bias reinforcement; Digital addict...,Cognitive Decline Risk
51997,51998,2034,AI-Augmented Society,Mixed,Southeast Asia,Young Adult (26-35),Undergraduate,Technology,Basic Assistants,7.9,...,68.04,73.49,56.73,59.71,25.88,52.13,42.74,Greater scientific discovery rates,Memory atrophy from AI offloading,Stagnant / Moderate
51998,51999,2063,Symbiotic Intelligence Age,Mixed,Europe,Elder (65+),Primary,Business,Full AGI Integration,38.1,...,83.96,63.76,75.91,65.16,86.20,60.20,47.62,Personalized learning pathways; Increased prod...,Skill atrophy in non-AI domains; Declining han...,Stagnant / Moderate
51999,52000,2052,Cognitive Co-Evolution,Pessimistic,East Asia,Adult (36-50),Primary,Engineering,Multi-modal AI,31.7,...,53.57,50.89,72.67,50.12,73.36,45.66,18.42,Greater scientific discovery rates,Polarization through AI echo chambers; Reduced...,Cognitive Decline Risk

In [20]:
df = df.drop(columns= ['Learning_Speed','Human_Decision_Making_Involvement','Social_Interaction_Quality'])
df

,Row_ID,Year,Era,Scenario,Region,Demographic_Group,Education_Level,Profession,AI_Tool_Category,Weekly_AI_Usage_Hours,...,Emotional_Intelligence,Innovation_Rate,Cognitive_Load_Index,Mental_Wellbeing_Score,AI_Tool_Proficiency,Adaptability_Score,Attention_Span_Minutes,Positive_Effects_of_AI,Negative_Effects_of_AI,Outcome_Label
0,1,2064,Symbiotic Intelligence Age,Pessimistic,East Asia,Young Adult (26-35),Undergraduate,Technology,AGI-Adjacent Tools,28.2,...,48.54,38.73,75.10,47.70,64.66,40.02,24.16,Cross-domain creativity boosts,Reduced independent thinking; Algorithmic bias...,Cognitive Decline Risk
1,2,2029,AI Mainstream Adoption,Mixed,Latin America,Senior (51-65),Undergraduate,Healthcare,NaN,10.0,...,73.40,42.50,52.64,74.85,28.18,57.00,46.35,Democratized access to expertise; Broader know...,Memory atrophy from AI offloading,Stagnant / Moderate
2,3,2047,Post-Singularity Transition,Neutral,Latin America,Youth (18-25),Secondary,Science & Research,Analytical AI,28.0,...,64.49,57.68,60.50,82.08,42.99,56.79,37.30,Faster skill acquisition,Privacy erosion through behavioral data,Stagnant / Moderate
3,4,2069,Symbiotic Intelligence Age,Neutral,East Asia,Senior (51-65),PhD/Research,Technology,Full AGI Integration,35.2,...,64.50,67.88,60.15,55.34,66.65,65.33,56.93,Reduced cognitive load on repetitive tasks,Decreased social bonding,Positive Growth
4,5,2048,Post-Singularity Transition,Optimistic,South Asia,Young Adult (26-35),Undergraduate,Entrepreneurship,Multi-modal AI,24.4,...,69.62,78.38,61.62,77.47,50.39,75.56,42.53,Increased productivity for deep work; Reduced ...,NaN,Positive Growth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51995,51996,2069,Symbiotic Intelligence Age,Mixed,South Asia,Young Adult (26-35),PhD/Research,Technology,Full AGI Integration,44.6,...,59.00,70.32,74.96,69.43,78.25,51.84,43.29,Faster skill acquisition,Algorithmic bias reinforcement; Memory atrophy...,Stagnant / Moderate
51996,51997,2052,Cognitive Co-Evolution,Pessimistic,South Asia,Youth (18-25),PhD/Research,Skilled Trades,Multi-modal AI,34.4,...,52.83,38.60,71.73,39.15,66.04,59.52,37.75,NaN,Algorithmic bias reinforcement; Digital addict...,Cognitive Decline Risk
51997,51998,2034,AI-Augmented Society,Mixed,Southeast Asia,Young Adult (26-35),Undergraduate,Technology,Basic Assistants,7.9,...,59.18,39.78,56.73,59.71,25.88,52.13,42.74,Greater scientific discovery rates,Memory atrophy from AI offloading,Stagnant / Moderate
51998,51999,2063,Symbiotic Intelligence Age,Mixed,Europe,Elder (65+),Primary,Business,Full AGI Integration,38.1,...,54.58,58.71,75.91,65.16,86.20,60.20,47.62,Personalized learning pathways; Increased prod...,Skill atrophy in non-AI domains; Declining han...,Stagnant / Moderate
51999,52000,2052,Cognitive Co-Evolution,Pessimistic,East Asia,Adult (36-50),Primary,Engineering,Multi-modal AI,31.7,...,50.72,55.02,72.67,50.12,73.36,45.66,18.42,Greater scientific discovery rates,Polarization through AI echo chambers; Reduced...,Cognitive Decline Risk