# Project 4

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\Asus\Downloads\data analytics project 1\project analysis python\Job Posts.csv")
df

,Unnamed: 0,Job_Title,Job_Description,Job_Link
0,0,"Data Scientist (NiFi, DHF)",EducationBachelor's DegreeSkillsSQLTime Manage...,https://www.simplyhired.com/job/Tq4KqCrotc06Fp...
1,1,Data Scientist - Defense & Intelligence,EducationBachelor's DegreeSkillsNoSQLSQL401(k)...,https://www.simplyhired.com/job/OF7HNEC0sGEgBA...
2,2,Fall 2019/Winter 2020 Applied Science Machine ...,EducationDoctoral DegreeMaster's DegreeSkillsN...,https://www.simplyhired.com/job/WaFb8rbhCLxehi...
3,3,Applied Scientist Fall/Winter 2019 Internship ...,EducationDoctoral DegreeMaster's DegreeSkillsN...,https://www.simplyhired.com/job/BL2wIHWVfwAAgw...
4,4,"Data Scientist/Engineer (HDF, NiFi)",EducationBachelor's DegreeMaster's DegreeDocto...,https://www.simplyhired.com/job/1H_ga33Kqka5Ot...
...,...,...,...,...
9062,9062,Senior Business Services Analyst,\r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...,https://www.careerbuilder.com/job/J3T26Q6VDXW9...
9063,9063,AVP of Corporate Strategy & Business Strategy,\r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...,https://www.careerbuilder.com/job/J3N4Z26H1LX0...
9064,9064,Business Analyst - Registered Nurse,\r\r\r\r\r\nCompany Overview:\r\r\r\r\r\nCreat...,https://www.careerbuilder.com/job/JDD66078BTB8...
9065,9065,Systems Analyst,\r\r\r\r\r\nA leading consultancy is recruitin...,https://www.careerbuilder.com/job/J3Q0PN78ZKRP...
9066,9066,Sales & Marketing Team Lead - Competative Spor...,\r\r\r\r\r\nMCO Orlando is currently offering ...,https://www.careerbuilder.com/job/J2Y43469NDQ7...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9067 entries, 0 to 9066
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       9067 non-null   int64
 1   Job_Title        9067 non-null   object
 2   Job_Description  9067 non-null   object
 3   Job_Link         9067 non-null   object
dtypes: int64(1), object(3)
memory usage: 283.5+ KB

In [7]:
df.isnull().sum()

Unnamed: 0         0
Job_Title          0
Job_Description    0
Job_Link           0
dtype: int64

In [8]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9062    False
9063    False
9064    False
9065    False
9066    False
Length: 9067, dtype: bool

In [9]:
df.set_index('Job_Title')

,Unnamed: 0,Job_Description,Job_Link
Job_Title,,,
"Data Scientist (NiFi, DHF)",0,EducationBachelor's DegreeSkillsSQLTime Manage...,https://www.simplyhired.com/job/Tq4KqCrotc06Fp...
Data Scientist - Defense & Intelligence,1,EducationBachelor's DegreeSkillsNoSQLSQL401(k)...,https://www.simplyhired.com/job/OF7HNEC0sGEgBA...
Fall 2019/Winter 2020 Applied Science Machine Learning/Deep Learning Intern,2,EducationDoctoral DegreeMaster's DegreeSkillsN...,https://www.simplyhired.com/job/WaFb8rbhCLxehi...
Applied Scientist Fall/Winter 2019 Internship - Natural Language Processing,3,EducationDoctoral DegreeMaster's DegreeSkillsN...,https://www.simplyhired.com/job/BL2wIHWVfwAAgw...
"Data Scientist/Engineer (HDF, NiFi)",4,EducationBachelor's DegreeMaster's DegreeDocto...,https://www.simplyhired.com/job/1H_ga33Kqka5Ot...
...,...,...,...
Senior Business Services Analyst,9062,\r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...,https://www.careerbuilder.com/job/J3T26Q6VDXW9...
AVP of Corporate Strategy & Business Strategy,9063,\r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...,https://www.careerbuilder.com/job/J3N4Z26H1LX0...
Business Analyst - Registered Nurse,9064,\r\r\r\r\r\nCompany Overview:\r\r\r\r\r\nCreat...,https://www.careerbuilder.com/job/JDD66078BTB8...
Systems Analyst,9065,\r\r\r\r\r\nA leading consultancy is recruitin...,https://www.careerbuilder.com/job/J3Q0PN78ZKRP...
Sales & Marketing Team Lead - Competative Sports Enthusiast,9066,\r\r\r\r\r\nMCO Orlando is currently offering ...,https://www.careerbuilder.com/job/J2Y43469NDQ7...

In [12]:
df2 = df.rename(columns= {'Job_Title': 'Nama Pekerjaan', 'Job_Description':'Deskripsi Pekerjaan', 'Job_Link': 'Tautan Pekerjaan'})
df2

,Unnamed: 0,Nama Pekerjaan,Deskripsi Pekerjaan,Tautan Pekerjaan
0,0,"Data Scientist (NiFi, DHF)",EducationBachelor's DegreeSkillsSQLTime Manage...,https://www.simplyhired.com/job/Tq4KqCrotc06Fp...
1,1,Data Scientist - Defense & Intelligence,EducationBachelor's DegreeSkillsNoSQLSQL401(k)...,https://www.simplyhired.com/job/OF7HNEC0sGEgBA...
2,2,Fall 2019/Winter 2020 Applied Science Machine ...,EducationDoctoral DegreeMaster's DegreeSkillsN...,https://www.simplyhired.com/job/WaFb8rbhCLxehi...
3,3,Applied Scientist Fall/Winter 2019 Internship ...,EducationDoctoral DegreeMaster's DegreeSkillsN...,https://www.simplyhired.com/job/BL2wIHWVfwAAgw...
4,4,"Data Scientist/Engineer (HDF, NiFi)",EducationBachelor's DegreeMaster's DegreeDocto...,https://www.simplyhired.com/job/1H_ga33Kqka5Ot...
...,...,...,...,...
9062,9062,Senior Business Services Analyst,\r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...,https://www.careerbuilder.com/job/J3T26Q6VDXW9...
9063,9063,AVP of Corporate Strategy & Business Strategy,\r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...,https://www.careerbuilder.com/job/J3N4Z26H1LX0...
9064,9064,Business Analyst - Registered Nurse,\r\r\r\r\r\nCompany Overview:\r\r\r\r\r\nCreat...,https://www.careerbuilder.com/job/JDD66078BTB8...
9065,9065,Systems Analyst,\r\r\r\r\r\nA leading consultancy is recruitin...,https://www.careerbuilder.com/job/J3Q0PN78ZKRP...
9066,9066,Sales & Marketing Team Lead - Competative Spor...,\r\r\r\r\r\nMCO Orlando is currently offering ...,https://www.careerbuilder.com/job/J2Y43469NDQ7...

In [15]:
df2.set_index('Nama Pekerjaan')

,Unnamed: 0,Deskripsi Pekerjaan,Tautan Pekerjaan
Nama Pekerjaan,,,
"Data Scientist (NiFi, DHF)",0,EducationBachelor's DegreeSkillsSQLTime Manage...,https://www.simplyhired.com/job/Tq4KqCrotc06Fp...
Data Scientist - Defense & Intelligence,1,EducationBachelor's DegreeSkillsNoSQLSQL401(k)...,https://www.simplyhired.com/job/OF7HNEC0sGEgBA...
Fall 2019/Winter 2020 Applied Science Machine Learning/Deep Learning Intern,2,EducationDoctoral DegreeMaster's DegreeSkillsN...,https://www.simplyhired.com/job/WaFb8rbhCLxehi...
Applied Scientist Fall/Winter 2019 Internship - Natural Language Processing,3,EducationDoctoral DegreeMaster's DegreeSkillsN...,https://www.simplyhired.com/job/BL2wIHWVfwAAgw...
"Data Scientist/Engineer (HDF, NiFi)",4,EducationBachelor's DegreeMaster's DegreeDocto...,https://www.simplyhired.com/job/1H_ga33Kqka5Ot...
...,...,...,...
Senior Business Services Analyst,9062,\r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...,https://www.careerbuilder.com/job/J3T26Q6VDXW9...
AVP of Corporate Strategy & Business Strategy,9063,\r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...,https://www.careerbuilder.com/job/J3N4Z26H1LX0...
Business Analyst - Registered Nurse,9064,\r\r\r\r\r\nCompany Overview:\r\r\r\r\r\nCreat...,https://www.careerbuilder.com/job/JDD66078BTB8...
Systems Analyst,9065,\r\r\r\r\r\nA leading consultancy is recruitin...,https://www.careerbuilder.com/job/J3Q0PN78ZKRP...
Sales & Marketing Team Lead - Competative Sports Enthusiast,9066,\r\r\r\r\r\nMCO Orlando is currently offering ...,https://www.careerbuilder.com/job/J2Y43469NDQ7...