# Project 2

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"C:\Users\Asus\Downloads\data analytics project 1\project analysis python\nba_dailyleaders_full.csv")
df

,Player,Tm,Opp,Result,MP,FG,FGA,FG%,3P,3PA,...,TRB,AST,STL,BLK,TOV,PF,PTS,+/-,GmSc,Date
0,Luka Dončić,LAL,GSW,L,40:59,17,27,0.630,2,10,...,12,9,2,1,3,1,43,-8.0,38.9,2025-10-21
1,Alperen Şengün,HOU,OKC,L,48:53,12,24,0.500,5,8,...,11,7,2,1,4,5,39,9.0,33.1,2025-10-21
2,Jimmy Butler,GSW,LAL,W,34:44,7,14,0.500,1,2,...,5,4,1,0,1,4,31,20.0,27.5,2025-10-21
3,Shai Gilgeous-Alexander,OKC,HOU,W,47:13,12,26,0.462,1,9,...,5,5,2,2,3,2,35,3.0,24.6,2025-10-21
4,Austin Reaves,LAL,GSW,L,36:20,9,16,0.563,1,5,...,5,9,2,0,5,5,26,-14.0,20.4,2025-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28563,Nikola Topić,OKC,SAS,W,0:46,0,0,NaN,0,0,...,0,0,0,0,0,0,0,-2.0,0.0,2026-05-26
28564,Aaron Wiggins,OKC,SAS,W,0:46,0,0,NaN,0,0,...,0,0,0,0,0,1,0,-2.0,-0.4,2026-05-26
28565,Mason Plumlee,SAS,OKC,L,2:13,0,0,NaN,0,0,...,1,0,0,0,0,2,0,1.0,-0.5,2026-05-26
28566,Bismack Biyombo,SAS,OKC,L,2:13,0,0,NaN,0,0,...,1,0,0,0,1,1,0,1.0,-0.7,2026-05-26
28567,Luke Kornet,SAS,OKC,L,8:09,0,1,0.000,0,0,...,1,0,0,0,0,3,0,-6.0,-1.2,2026-05-26

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28568 entries, 0 to 28567
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  28568 non-null  object
 1   Tm      28568 non-null  object
 2   Opp     28568 non-null  object
 3   Result  28568 non-null  object
 4   MP      28568 non-null  object
 5   FG      28568 non-null  int64
 6   FGA     28568 non-null  int64
 7   FG%     27069 non-null  float64
 8   3P      28568 non-null  int64
 9   3PA     28568 non-null  int64
 10  3P%     22822 non-null  float64
 11  FT      28568 non-null  int64
 12  FTA     28568 non-null  int64
 13  FT%     15952 non-null  float64
 14  ORB     28568 non-null  int64
 15  DRB     28568 non-null  int64
 16  TRB     28568 non-null  int64
 17  AST     28568 non-null  int64
 18  STL     28568 non-null  int64
 19  BLK     28568 non-null  int64
 20  TOV     28568 non-null  int64
 21  PF      28568 non-null  int64
 22  PTS     28568 non-null  int64
 23  +/-     28538 non-null  float64
 24  GmSc    28568 non-null  float64
 25  Date    28568 non-null  object
dtypes: float64(5), int64(15), object(6)
memory usage: 5.7+ MB

In [5]:
df.describe()

,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-,GmSc
count,28568.000000,28568.000000,27069.000000,28568.000000,28568.000000,22822.000000,28568.000000,28568.000000,15952.000000,28568.000000,28568.000000,28568.000000,28568.000000,28568.000000,28568.000000,28568.000000,28568.000000,28568.000000,28538.000000,28568.000000
mean,3.844336,8.179222,0.459479,1.216571,3.389492,0.332069,1.696584,2.169490,0.767912,1.046696,2.974517,4.021213,2.442873,0.773138,0.447669,1.268937,1.842271,10.601827,0.000000,8.640657
std,3.163654,5.853213,0.238910,1.481347,3.022530,0.285122,2.387571,2.857568,0.279421,1.380795,2.584013,3.325122,2.555018,0.992899,0.812394,1.397641,1.467675,8.672527,11.937653,7.700130
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-60.000000,-10.200000
25%,1.000000,4.000000,0.333000,0.000000,1.000000,0.000000,0.000000,0.000000,0.500000,0.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,1.000000,4.000000,-7.000000,2.600000
50%,3.000000,7.000000,0.471000,1.000000,3.000000,0.333000,1.000000,2.000000,0.846000,1.000000,2.000000,3.000000,2.000000,0.000000,0.000000,1.000000,2.000000,9.000000,0.000000,7.300000
75%,6.000000,12.000000,0.600000,2.000000,5.000000,0.500000,2.000000,3.000000,1.000000,2.000000,4.000000,6.000000,4.000000,1.000000,1.000000,2.000000,3.000000,16.000000,7.000000,13.300000
max,20.000000,45.000000,1.000000,12.000000,22.000000,1.000000,36.000000,43.000000,1.000000,13.000000,19.000000,25.000000,23.000000,8.000000,12.000000,11.000000,6.000000,83.000000,52.000000,60.500000

In [6]:
df

,Player,Tm,Opp,Result,MP,FG,FGA,FG%,3P,3PA,...,TRB,AST,STL,BLK,TOV,PF,PTS,+/-,GmSc,Date
0,Luka Dončić,LAL,GSW,L,40:59,17,27,0.630,2,10,...,12,9,2,1,3,1,43,-8.0,38.9,2025-10-21
1,Alperen Şengün,HOU,OKC,L,48:53,12,24,0.500,5,8,...,11,7,2,1,4,5,39,9.0,33.1,2025-10-21
2,Jimmy Butler,GSW,LAL,W,34:44,7,14,0.500,1,2,...,5,4,1,0,1,4,31,20.0,27.5,2025-10-21
3,Shai Gilgeous-Alexander,OKC,HOU,W,47:13,12,26,0.462,1,9,...,5,5,2,2,3,2,35,3.0,24.6,2025-10-21
4,Austin Reaves,LAL,GSW,L,36:20,9,16,0.563,1,5,...,5,9,2,0,5,5,26,-14.0,20.4,2025-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28563,Nikola Topić,OKC,SAS,W,0:46,0,0,NaN,0,0,...,0,0,0,0,0,0,0,-2.0,0.0,2026-05-26
28564,Aaron Wiggins,OKC,SAS,W,0:46,0,0,NaN,0,0,...,0,0,0,0,0,1,0,-2.0,-0.4,2026-05-26
28565,Mason Plumlee,SAS,OKC,L,2:13,0,0,NaN,0,0,...,1,0,0,0,0,2,0,1.0,-0.5,2026-05-26
28566,Bismack Biyombo,SAS,OKC,L,2:13,0,0,NaN,0,0,...,1,0,0,0,1,1,0,1.0,-0.7,2026-05-26
28567,Luke Kornet,SAS,OKC,L,8:09,0,1,0.000,0,0,...,1,0,0,0,0,3,0,-6.0,-1.2,2026-05-26

In [7]:
df.isnull().sum()

Player        0
Tm            0
Opp           0
Result        0
MP            0
FG            0
FGA           0
FG%        1499
3P            0
3PA           0
3P%        5746
FT            0
FTA           0
FT%       12616
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
+/-          30
GmSc          0
Date          0
dtype: int64

In [8]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
28563    False
28564    False
28565    False
28566    False
28567    False
Length: 28568, dtype: bool

In [9]:
df

,Player,Tm,Opp,Result,MP,FG,FGA,FG%,3P,3PA,...,TRB,AST,STL,BLK,TOV,PF,PTS,+/-,GmSc,Date
0,Luka Dončić,LAL,GSW,L,40:59,17,27,0.630,2,10,...,12,9,2,1,3,1,43,-8.0,38.9,2025-10-21
1,Alperen Şengün,HOU,OKC,L,48:53,12,24,0.500,5,8,...,11,7,2,1,4,5,39,9.0,33.1,2025-10-21
2,Jimmy Butler,GSW,LAL,W,34:44,7,14,0.500,1,2,...,5,4,1,0,1,4,31,20.0,27.5,2025-10-21
3,Shai Gilgeous-Alexander,OKC,HOU,W,47:13,12,26,0.462,1,9,...,5,5,2,2,3,2,35,3.0,24.6,2025-10-21
4,Austin Reaves,LAL,GSW,L,36:20,9,16,0.563,1,5,...,5,9,2,0,5,5,26,-14.0,20.4,2025-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28563,Nikola Topić,OKC,SAS,W,0:46,0,0,NaN,0,0,...,0,0,0,0,0,0,0,-2.0,0.0,2026-05-26
28564,Aaron Wiggins,OKC,SAS,W,0:46,0,0,NaN,0,0,...,0,0,0,0,0,1,0,-2.0,-0.4,2026-05-26
28565,Mason Plumlee,SAS,OKC,L,2:13,0,0,NaN,0,0,...,1,0,0,0,0,2,0,1.0,-0.5,2026-05-26
28566,Bismack Biyombo,SAS,OKC,L,2:13,0,0,NaN,0,0,...,1,0,0,0,1,1,0,1.0,-0.7,2026-05-26
28567,Luke Kornet,SAS,OKC,L,8:09,0,1,0.000,0,0,...,1,0,0,0,0,3,0,-6.0,-1.2,2026-05-26

In [13]:
df.set_index("Player")

,Tm,Opp,Result,MP,FG,FGA,FG%,3P,3PA,3P%,...,TRB,AST,STL,BLK,TOV,PF,PTS,+/-,GmSc,Date
Player,,,,,,,,,,,,,,,,,,,,,
Luka Dončić,LAL,GSW,L,40:59,17,27,0.630,2,10,0.200,...,12,9,2,1,3,1,43,-8.0,38.9,2025-10-21
Alperen Şengün,HOU,OKC,L,48:53,12,24,0.500,5,8,0.625,...,11,7,2,1,4,5,39,9.0,33.1,2025-10-21
Jimmy Butler,GSW,LAL,W,34:44,7,14,0.500,1,2,0.500,...,5,4,1,0,1,4,31,20.0,27.5,2025-10-21
Shai Gilgeous-Alexander,OKC,HOU,W,47:13,12,26,0.462,1,9,0.111,...,5,5,2,2,3,2,35,3.0,24.6,2025-10-21
Austin Reaves,LAL,GSW,L,36:20,9,16,0.563,1,5,0.200,...,5,9,2,0,5,5,26,-14.0,20.4,2025-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Nikola Topić,OKC,SAS,W,0:46,0,0,NaN,0,0,NaN,...,0,0,0,0,0,0,0,-2.0,0.0,2026-05-26
Aaron Wiggins,OKC,SAS,W,0:46,0,0,NaN,0,0,NaN,...,0,0,0,0,0,1,0,-2.0,-0.4,2026-05-26
Mason Plumlee,SAS,OKC,L,2:13,0,0,NaN,0,0,NaN,...,1,0,0,0,0,2,0,1.0,-0.5,2026-05-26
Bismack Biyombo,SAS,OKC,L,2:13,0,0,NaN,0,0,NaN,...,1,0,0,0,1,1,0,1.0,-0.7,2026-05-26
Luke Kornet,SAS,OKC,L,8:09,0,1,0.000,0,0,NaN,...,1,0,0,0,0,3,0,-6.0,-1.2,2026-05-26

In [20]:
df.pivot_table(index = 'Player', values = 'FG%', aggfunc='mean')

                      FG%
Player
A.J. Green       0.410205
A.J. Lawson      0.293480
AJ Johnson       0.254025
Aaron Gordon     0.450615
Aaron Holiday    0.406068
...                   ...
Zach LaVine      0.468000
Zeke Nnaji       0.479543
Ziaire Williams  0.403821
Zion Williamson  0.600419
Zyon Pullin      0.833500

[582 rows x 1 columns]

In [24]:
df.rename(columns= {'Tm':'Team', 'Opp':'Adversary'})

,Player,Team,Adversary,Result,MP,FG,FGA,FG%,3P,3PA,...,TRB,AST,STL,BLK,TOV,PF,PTS,+/-,GmSc,Date
0,Luka Dončić,LAL,GSW,L,40:59,17,27,0.630,2,10,...,12,9,2,1,3,1,43,-8.0,38.9,2025-10-21
1,Alperen Şengün,HOU,OKC,L,48:53,12,24,0.500,5,8,...,11,7,2,1,4,5,39,9.0,33.1,2025-10-21
2,Jimmy Butler,GSW,LAL,W,34:44,7,14,0.500,1,2,...,5,4,1,0,1,4,31,20.0,27.5,2025-10-21
3,Shai Gilgeous-Alexander,OKC,HOU,W,47:13,12,26,0.462,1,9,...,5,5,2,2,3,2,35,3.0,24.6,2025-10-21
4,Austin Reaves,LAL,GSW,L,36:20,9,16,0.563,1,5,...,5,9,2,0,5,5,26,-14.0,20.4,2025-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28563,Nikola Topić,OKC,SAS,W,0:46,0,0,NaN,0,0,...,0,0,0,0,0,0,0,-2.0,0.0,2026-05-26
28564,Aaron Wiggins,OKC,SAS,W,0:46,0,0,NaN,0,0,...,0,0,0,0,0,1,0,-2.0,-0.4,2026-05-26
28565,Mason Plumlee,SAS,OKC,L,2:13,0,0,NaN,0,0,...,1,0,0,0,0,2,0,1.0,-0.5,2026-05-26
28566,Bismack Biyombo,SAS,OKC,L,2:13,0,0,NaN,0,0,...,1,0,0,0,1,1,0,1.0,-0.7,2026-05-26
28567,Luke Kornet,SAS,OKC,L,8:09,0,1,0.000,0,0,...,1,0,0,0,0,3,0,-6.0,-1.2,2026-05-26